version: "3.9"
services:
  database:
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jordan.mack37@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  backend:
    ports:
      - "3030:3030"
    env_file:
      - ./.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
  frontend:
    ports:
      - "5173:5173"
    env_file:
      - ./.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
volumes:
  pgadmin-data:
