version: "3.9"
services:
  postgresql:
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    container_name: postgresql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
  fastify:
    ports:
      - "3030:3030"
    env_file:
      - ./.env
    build:
      context: ./fastify
      dockerfile: Dockerfile
    volumes:
      - ./fastify:/usr/src/app
    container_name: fastify
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
  frontend:
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: react
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
