version: "3.9"
services:
  database:
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
  backend:
    ports:
      - "3030:3030"
    env_file:
      - ./.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
  frontend:
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "always"
